### ISSUE TITLE
Install Movement CLI page link and docs info

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/movement-docs#17]
@Rahat-ch @PrasoonPratham I'm getting ready to update the docs relating to Aptos CLI so they are relevant to the changes to Movement CLI (which replaces Aptos CLI).

On [this page](https://docs.movementnetwork.xyz/Developers/setup) I see a link to Install Aptos CLI but the link goes to https://docs.movementnetwork.xyz/.

1. Do you have a page in mind, or is there one on the docs site already, for installing Movement CLI? I'm not quite sure where to update installation instructions. 

If you're not sure where it would go, may I suggest a Developer Tooling section?

2. Or if you prefer to make the updates, basically the Movement CLI crate is at

https://github.com/movementlabsxyz/aptos-core/tree/movement/crates/aptos

for developers who want to dive into the source code

and the syntax is changed as follows:

Wherever you have the `aptos` command in Aptos CLI, simply substitute `movement` for it, in the docs. 

So `aptos move build` becomes `movement move build`.

This is different than the old Movement CLI, where you would use `movement aptos move build` because both Aptos and Sui CLI were embedded into that one Movement CLI. 

Movement CLI now is focused on supporting Aptos Move exclusively at first, hence removing the need to specify `aptos` in specific CLI commands.

3. To install Movement CLI, clone the `movement` branch of https://github.com/movementlabsxyz/aptos-core/ and cd into it.

Then run `cargo build -p movement`.

This generates the `target/debug/movement` executable, which you can copy into your `bin` or add it to your `PATH` depending on your system config.

Example of copying `movement` to `bin` on Mac or Linux:
```
sudo cp target/debug/movement /usr/local/bin/
```

Hope this helps. Please let me know if you'd like me to add any of it anywhere specifically in the docs.

**Comment by PrasoonPratham** [comment]
This link was supposed to go to the [Aptos CLI installation](https://aptos.dev/en/build/cli) instructions. Going forward we can have an installation instructions on [this page](https://docs.movementnetwork.xyz/Developers/setup) itself with the new movement CLI.

**Comment by andygolay** [comment]
Ok so I can add the installation instructions under the Aptos heading there?
 
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/1a5954da-e04a-455c-bcac-3e9ad39a3da4">

**Comment by PrasoonPratham** [comment]
Yeah that would be perfect. Let’s also clarify the movement CLI is analogous to the Aptos CLI and Sui is under development.

**Comment by andygolay** [comment]
Alright, submitted here: https://github.com/movementlabsxyz/movement-docs/pull/18
