### ISSUE TITLE
Feature Proposal: Cookbook Onboard (AI Assistant & Playground)

### ISSUE THREAD

**Issue by ClockRide** [movementlabsxyz/movement-docs#35]
Preview link: https://movement-labs-cookbook-onboard.vercel.app/

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Movement Labs resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Movement Labs, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity and Move language coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Movement-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

![image](https://github.com/user-attachments/assets/476ec00e-5e59-4a97-8cd2-82478d885f6a)

## Cookbook Onboard Playground
The Cookbook Onboard Playground embeds a Solidity IDE with smart contract templates displayed alongside the Ask Cookbook AI Assistant.

Developers can search for and deploy Cookbook’s entire smart contract library from your technical documentation.

Features:
- Deploy smart contracts or entire protocols to Movement without leaving Movement Lab's technical docs
- Acts as a free, no-code or low-code token and NFT launchpad
- Save source code as a Foundry, Hardhat, or Scaffold project or export it to Remix or Chain IDE in one click

![image](https://github.com/user-attachments/assets/d9b4e29f-0550-4ae6-9b33-d4be5fc34a9f)

**Comment by ClockRide** [comment]
PS: While working on the PR, we discovered some broken RPC URLs overlooked in #28 and proposed a fix for them in #34.

**Comment by AIWhispererDev** [comment]
hey have you recently updated it on new documentation? For example it says
"For more detailed information, you can refer to the [Movement Labs documentation](https://docs.movementlabs.xyz/developers/tutorials/build-dapp/solidity-dapp)."

this probably migrated to https://docs.movementnetwork.xyz/devs/tutorials/Build%20dApp/solidity

Is it mostly using docs for devnet?

Also which LLM is used for this?

**Comment by ClockRide** [comment]
> hey have you recently updated it on new documentation? For example it says "For more detailed information, you can refer to the [Movement Labs documentation](https://docs.movementlabs.xyz/developers/tutorials/build-dapp/solidity-dapp)."
> 
> this probably migrated to https://docs.movementnetwork.xyz/devs/tutorials/Build%20dApp/solidity
> 
> Is it mostly using docs for devnet?
> 
> Also which LLM is used for this?

It seems we had some broken or outdated links set as data sources, but that should now be resolved. Thanks for the feedback! It is using GPT-4o enriched with our own library of Web3 resources and data sources specific to the MovementLabs docs.
